### PR TITLE
Replace deprecated slash division in SCSS sources

### LINKED ISSUE #61: Breaking Change: Slash as Division
```
WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
15 │   @return if($input != 0, random($input) - $input/2, 0);
   │                                            ^^^^^^^^
   ╵
    node_modules/csshake/scss/_tools.scss 15:44                                 apply-random()
    node_modules/csshake/scss/_tools.scss 59:18                                 do-shake()
```

Therefor a small change should be done in scss/_tools.scss.

### PR DESCRIPTION
**Pull request by netwarex**
Fixes #61

### CODE REVIEW

**Comment by elrumordelaluz** [comment]
Hi @netwarex,
Does I have to make another change in order to allow `sass:math`? (long time I'm not using `sass`)

I am getting this error testing your PR:

```
Error: Invalid CSS after \"...($input) - math\": expected expression (e.g. 1px, bold), was \".div($input, 2), 0)\"
on line 21 of scss/_tools.scss
from line 9 of scss/csshake.scss\n>> turn if($input != 0, random($input) - math.div($input, 2), 0);"
```

**Comment by netwarex** [comment]
Maybe the sass version need to be updated. node-sass is deprecated, instead https://www.npmjs.com/package/sass should be used. This should solve the problem.

**Comment by netwarex** [comment]
@elrumordelaluz I have updated the dependencies, and removed the need of sass:math, instead using multiplying to do division.

**Comment by netwarex** [comment]
@elrumordelaluz Any update, is it fine? :)

**Comment by elrumordelaluz** [comment]
Looks good to me, thank you  @netwarex and sorry for the delay!

**Pull request merged**
