### PR TITLE
Add missing `shake-constant`

### PR DESCRIPTION
**Pull request by seb0zz**
Also add `.idea` folder from IntelliJ IDEs to `.gitignore`

### CODE REVIEW

**Comment by elrumordelaluz** [comment]
Hi @seb0zz don't understand why you need to have the `shake-constant` class as a new shake animation class when it [exists](https://github.com/elrumordelaluz/csshake/blob/master/scss/_tools.scss#L97) yet as a _helper class_. 

[Here](http://codepen.io/elrumordelaluz/pen/9c925051ea3ef55c5572e6e5405428a7) you have an example to see how it works, just apply the `shake-*` animation constantly.

**Comment by seb0zz** [comment]
Hi @elrumordelaluz thing is that I am using [css-modules](https://github.com/css-modules/css-modules). So I am not able to simply write something like `class="shake-constant"` in my markup. Also all my class names will be hashed on deployment and I do not load any plain CSS files from my server. So what I basically do (in the project using my fork) is:

```scss
@import "../../../node_modules/csshake/scss/csshake";

.callToActionShaking {
  @extend .callToAction;
  @extend .shake-constant;

  display: block;
}
```

That's why I need `shake-constant` to be defined ;-)

**Comment by elrumordelaluz** [comment]
`shake-constant` should be defined importing the file `csshake.scss` since it imports `_tools.scss` where is defined a variable `$prefix: 'shake' !default;` used in [some lines](https://github.com/elrumordelaluz/csshake/blob/master/scss/_tools.scss#L83-L98) to define the class `.#{$prefix}-constant === .shake-constant` inside each animation created. 
`shake-constant` does not have an independent behaviour, need to be used as a _modifier_ of a animation created through `do-shake()` mixin. 
Did you tried `@extend`ing `shake` or another `shake-*` animation?

**Comment by seb0zz** [comment]
Yes I tried that but then I am only able to get the shake effect on hover.

**Comment by elrumordelaluz** [comment]
Right. To have available this class you have to at least _process_ an animation thorugh the mixin. Creating a class `.shake-constant   { @include do-shake('shake-constant'); }` will give you the same situation of using `@extend .shake` (but in this case `.shake-constant`) and you'll need to call .shake-constant.shake-constant to have it constantly (like we talked before).

Did you tried importing the desired animation from `dist`? Do you have a repo or something with this working?

**Comment by elrumordelaluz** [comment]
@seb0zz you could do one of this two things:

```scss
@import "../../../node_modules/csshake/scss/csshake";
.yourClass {
  @extend .shake.shake-constant;
  ...
}
```

or 

```scss
@import "../../../node_modules/csshake/scss/csshake";

%myAnim { @include do-shake(); }
.yourClass {
  @extend %myAnim.shake-constant;
  ...
}
```

**Comment by seb0zz** [comment]
The first one works, thanks!

**Comment by elrumordelaluz** [comment]
cool! let me know if there's another behavior with css-modules.

**Pull request closed without merging**
